<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>s</string>
		<string>asm</string>
	</array>
	<key>name</key>
	<string>MIPS</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Assembler directives</string>
			<key>match</key>
			<string>\.\b(import|export|word)\b</string>
			<key>name</key>
			<string>storage.modifier.mips</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Registers by id $1, $2, ...</string>
			<key>match</key>
			<string>\$((3[01])|([12]?[0-9])|[0-9])</string>
			<key>name</key>
			<string>variable.parameter.mips</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Just the hardcoded instructions provided by the MIPS assembly language</string>
			<key>match</key>
			<string>\b(add|sub|mult|multu|div|divu|mfhi|mflo|lis|lw|sw|slt|sltu|beq|bne|jr|jalr)\b</string>
			<key>name</key>
			<string>support.function.source.mips</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Numbers like +12, -3, 55, 0x3F</string>
			<key>match</key>
			<string>\b((0(x|X)[0-9A-Fa-f]*)|((\-)?[0-9]*))\b</string>
			<key>name</key>
			<string>constant.numeric.mips</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Labels at line start: begin_repeat: add ...</string>
			<key>match</key>
			<string>\b[\w]+\b:</string>
			<key>name</key>
			<string>entity.name.tag.mips</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Single line comments</string>
			<key>match</key>
			<string>;.*$</string>
			<key>name</key>
			<string>comment.line.number-sign.mips</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.mips</string>
	<key>uuid</key>
	<string>f43b595a-700b-4f4f-a525-9c78c44d0254</string>
</dict>
</plist>
