mips241.js:
	# change this line in the makefile is emscripten is somewhere else
	~/Emscripten/emscripten/master/em++ --bind -o mips241.js bus.cc cpu.cc debug.cc disasm.cc embind.cc mem.cc # not main.cc!

